### ISSUE TITLE
ExAws.Config.retrieve_runtime_value getting throttled

### ISSUE THREAD

**Issue by chris-brace** [ex-aws/ex_aws#798]
### Environment

* Elixir & Erlang versions (elixir --version):
Elixir 1.11.4
Erlang/OTP 23 [erts-11.2.2.3] [source] [64-bit] [smp:2:1] [ds:2:1:10] [async-threads:1]

* ExAws version `mix deps |grep ex_aws`
```
      {:ex_aws, "~> 2.2.1"},
      {:ex_aws_ssm, "~> 2.1.0"},
      {:ex_aws_s3, "~> 2.1.0"},
      {:ex_aws_sts, "~> 2.1.0"},
      {:ex_aws_sqs, "~> 3.3.1"},
```

* HTTP client version. IE for hackney do `mix deps | grep hackney`
```
      {:hackney, "~> 1.17.4"},
```

### Current behavior

I am using Broadway's SQS module to listen to a queue. Every once and a while, since June 8th mid day EST, several of our environments have seen the VM crash after emitting many of the following messages very quickly:

```
GenServer S3Events.Consumer.Broadway.Producer_0 terminating
** (BadMapError) expected a map, got: {:error, {:http_error, 400, %{code: "Throttling", detail: "", message: "Rate exceeded", request_id: "a3c1cfc8-20ef-4579-94a3-120efef98375", type: "Sender"}}}
    (elixir 1.11.4) lib/map.ex:422: Map.take/2
    (ex_aws 2.2.1) lib/ex_aws/config.ex:91: ExAws.Config.retrieve_runtime_value/2
    (elixir 1.11.4) lib/stream.ex:572: anonymous fn/4 in Stream.map/2
    (elixir 1.11.4) lib/enum.ex:3776: Enumerable.List.reduce/3
    (elixir 1.11.4) lib/stream.ex:1609: Enumerable.Stream.do_each/4
    (elixir 1.11.4) lib/enum.ex:974: Enum.find/3
    (ex_aws 2.2.1) lib/ex_aws/config.ex:71: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1
    (stdlib 3.14.2) maps.erl:233: :maps.fold_1/3
Last message: {:"$gen_producer", {#PID<0.18472.0>, #Reference<0.4239996247.2497708033.129821>}, {:ask, 10}}
```

the relevant ex_aws config is 
```
config :ex_aws,
  secret_access_key: [{:awscli, "default", 30}],
  access_key_id: [{:awscli, "default", 30}],
  region: {:system, "AWS_REGION"},
  awscli_auth_adapter: ExAws.STS.AuthCache.AssumeRoleWebIdentityAdapter,
  role_session_name: "ex_aws_sts"
```

also, the VM is running in a kubernetes cluster, and the container is set up to use "service account tokens" in the way AWS advises. something like this, in the k8s config

```
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
...
    volumeMounts:
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
...
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
  - name: token-vol
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3600
          path: token
```
